imageFinder/imageFinder/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('web.urls', namespace="web")),#can be set to /web, lets leave it as home page
    url(r'^admin/', admin.site.urls),
    url(r'^tools/', include('tools.urls', namespace="tools")),
]

imageFinder/web/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
    url(r'^survey/$', views.survey, name='survey'),
    url(r'^opendocument/$', views.OpenDocument, name='OpenDocument'),
]

imageFinder/web/templates/web/index.html
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'web/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'web/bootstrap/css/bootstrap.css' %}"></script>
<script type="text/javascript" src="{% static 'web/jquery-3.1.0.min.js' %}"></script>
</head>



{% include "web/searchbar.html" %}

<div class="searchForm">
<form action="{% url 'web:survey'  %}" method="post">
{% csrf_token %}
	<p>Can you help us to describe this image?</p>
	<div style="">
		<img alt="" src="{% static 'web/'%}{{randomImg}}" style="width: 250px; border: 3px solid blue; display: inline-block;">
		<input type="hidden" name="imageID" value="{{img_id}}"/>
		<ul class="noStyle">
		{% for class in classes%}
			{% if class.image_class == 1 or class.image_class == 3 %} 
			<li class="autoFit">
				<input type="radio" name="survey" id="{{class.image_class}}" value="{{class.image_class}}">
				<label for="{{class.image_class}}">{{class.image_class_desc}}</label>
			</li>
			{% endif %}
		{% endfor %}
		</ul>
		<button class="btn btn-primary" type="submit" >Submit</button>
	</div>
</form>
</div>

imageFinder/web/templates/web/opendocument.html
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'web/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'web/bootstrap/css/bootstrap.css' %}"></script>
<script type="text/javascript" src="{% static 'web/jquery-3.1.0.min.js' %}"></script>

</head>
{% include "web/searchbar.html" %}
<table>
  <tbody>
    <tr>
	    <td style="text-align:center;">
	      <img src="{% static 'web/'%}{{img_loc}}"></img
	    </td>
	    <td rowspan=5 style="width:20%; height:400px; vertical-align:top;">
	    	<!-- This area is for Related images -->
	    	<div class="scrollable">
	    	<div class="relatedImages">
	    	Related Images
	    	</div>
	    	<!-- Related Images -->
	    	{% for key, doc in relatedDocs.items %}
	    	<div>
	    		<a href="{% url 'web:OpenDocument' %}?pmcid={{key}}&&img_loc={{doc.imgURL}}"><label>{{doc.title}}</label></a>
	    		<img src="{% static 'web/'%}{{doc.imgURL}}"> </img>
	    	</div>
	    	{% endfor %}
	    	</div>
	    </td>
    </tr>
    
    <tr>
      <td style="text-align:center; font-weight:bold">
        <h1>{{title}}</h1>
      </td>
    </tr>
    <tr>
      <td>
        <p>{{abstract}}</p>
      </td>
    </tr>
    <tr>
      <td>
        <p>DOI: {{doi}}</p>
        <p>Volume: {{volume}}</p>
        <p>year: {{year}}</p>
        <p>publisher: {{publisher}}</p>
      </td>
    </tr>
    <tr>
      <td>
        <a target="_blank" href="{{fullText}}">Full Text</a> | <a target="_blank" href="{{pdf}}">PDF</a>
      </td>
    </tr>
  </tbody>
</table>

<style>
img{
height:15em;
}
table{
	margin-left:2em;
}
.relatedImages{
	background-color:#00356B;
	color:white;
	
}
div.scrollable {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    overflow: auto;
}
</style>

imageFinder/web/templates/web/search.html
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'web/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'web/bootstrap/css/bootstrap.css' %}"></script>
<script type="text/javascript" src="{% static 'web/jquery-3.1.0.min.js' %}"></script>

</head>
{% include "web/searchbar.html" %}
<h1>Search Results</h1>
<h3>The search term was: <b style="color: Blue">{{term}}</b></h3>
<h3>Number of documents with images found: <b style="color: Blue">{{imageCount}}</b></h3>
<h4>Fields used: {{advSearch}}</h4>
<table>
<tbody>
<tr >

{% for key, img in results.items %}
{% if not forloop.counter|divisibleby:6 and not forloop.first %}
<td>

	<a href="{% url 'web:OpenDocument' %}?pmcid={{key}}&&img_loc={{img.imgURL}}"><!-- This is not how we should handle images -->
		<label>{{img.title}}</label>
		<img class="" src="{% static 'web/'%}{{img.imgURL}}"></img>
	</a>
	
</td>
{% else %}
</tr>
<tr>
<td>

	<a href="{% url 'web:OpenDocument' %}?pmcid={{key}}&&img_loc={{img.imgURL}}"><!-- This is not how we should handle images -->
		<label>{{img.title}}</label>
		<img class="" src="{% static 'web/'%}{{img.imgURL}}"></img>
	</a>
</td>
{% endif %}
{% endfor %}

</tr>
</tbody>
</table>

<style>
.table {
    width: 250px;
    height: 250px;
    border: 3px solid blue;
    }
td{
	width:18%;
	border-bottom:solid blue;
	vertical-align:top;
	padding:5px;
}
tr{
	width:100%
}

</style>

imageFinder/web/templates/web/searchbar.html
{% load staticfiles %}
<script type="text/javascript" src="{% static 'web/jquery-3.1.0.min.js' %}"></script>

<div class="banner">
	<a class="title" href="{% url 'web:index' %}"><h2>Yale Image Finder</h2></a>
</div>
<div class="searchForm">
<div>
<form action="{% url 'web:search' %}" method="post">
{% csrf_token %}
<div style="padding-bottom:10px;">
<input class="searchBar" type="text" size="50" name="searchTerm" style="height:30px; margin-bottom:0px;"/>
		<button class="btn btn-primary" type="submit" >Search</button>
		<select name="classes" class="classddl">
		<option  value="all">All</option>
		{% for class in classes%}
		<option  id="{{class.image_class}}" value="{{class.image_class}}">{{class.image_class_desc}}</option>
		{% endfor %}
		</select>
		<a id="advancedOptions"><label>Advanced options</label></a>
</div>
		
		<div class="advancedSearch">
		<input type="checkbox" name="advSearch" value="image_text_high_recall" id="image_text_high_recall"/>
			<label for="image_text_high_recall">Image Text (High Recall)</label>
		<input type="checkbox" name="advSearch" value="image_text_high_precision" id="image_text_high_precision"/>
			<label for="image_text_high_precision">Image Text (High Precision)</label>
		<input type="checkbox" name="advSearch" value="caption" id="caption"/>
			<label for="caption">Caption</label>
		<input checked="checked" type="checkbox" name="advSearch" value="abstract" id="abstract"/>
			<label for="abstract">Abstract</label>
		<input checked="checked" type="checkbox" name="advSearch" value="title" id="title"/>
			<label for="title">Title</label>
		<input type="checkbox" name="advSearch" value="full_text" id="full_text"/>
			<label for="full_text">Full Text</label>
		</div>
		
</form>
</div>
</div> 

<style>
.advancedSearch{
	display:none;
}
.advancedSearch label{
	display:inline;
}
.classddl{
	margin-left:1em;
	margin-bottom:0px;
	width:8em;
}
a.title{
	color:white;
}
a.title:visited{
	color:white;
}
a.title:hover{
	color:white;
}
</style>

<script>
	$('#advancedOptions').click(function(){
		$('.advancedSearch').toggle();
		
	});
</script>